### PR TITLE
Halt create command if in root of meteor project

### PR DESCRIPTION
**Pull request by thancock20**
As discussed in #63.

### CODE REVIEW

**Comment by thancock20** [comment]
So, apparently the tests fail on node v0.12.10, although they pass on node v4.0.0
"undefined is not a function"
Did `fs.existsSync` not exist yet in v0.12.10?

Never mind, there's a `checkFileExists` function in the utils file. I should have used that in the first place.

**Comment by thancock20** [comment]
Switching to `checkFileExists` didn't fix the failures on v0.12.10
Not sure why it's failing there. I'll have to come back to it later.

**Comment by sungwoncho** [comment]
My hunch is that there is nothing wrong with this PR, but [this line](https://github.com/mantrajs/mantra-cli/blob/master/lib/utils.js#L25) is failing. Maybe `Object.assign` was not implemented in 0.12.

I'll look into it on the weekends.

**Comment by sungwoncho** [comment]
by the way, looking at the [Travis log](https://travis-ci.org/mantrajs/mantra-cli/jobs/168819423), I cannot pinpoint the exact line where the error occurred because there is no source map. The stack trace points to files under `/dist` which is compiled and garbled.

If we can fix this, it will come in handy in the future when debugging. Any ideas?

**Comment by sungwoncho** [comment]
Thanks. Fixed the test in https://github.com/mantrajs/mantra-cli/commit/09ba433d9f7be6578c5347e8f96702f924714c46

**Pull request merged**
