### PR TITLE
Feature/generate stories

### LINKED ISSUE #72: storybook support
I'm wondering if the community needs React Storybook support. Let's discuss here.

### PR DESCRIPTION
**Pull request by macrozone**
fixes https://github.com/mantrajs/mantra-cli/issues/72

Todo:
- [x] generate components/.stories/index.js
- [x] generate storybook-file when generating a component
- [x] generate storybook-file for the corresponding component when generating a container
- [x] import the stories in the module's components/.stories/index.js
- [x] add storybook-dependencies and commands to package.tt
- [x] define template for /.storybook/config.js
- [x] define template for /.storybook/webpack.config.js
- [x] add import/require in /.storybook/config.js when a new module is created
- [ ] make generating of storybook optional

### CODE REVIEW

**Comment by macrozone** [comment]
@sungwoncho maybe you can help with `add import/require in /.storybook/config.js when a new module is created`

We need to generate something like this for every module:

```
function loadStories() {
  require('../client/modules/core/components/.stories');
  require('../client/modules/comments/components/.stories');
}
```

But i think that's not so important and I would suggest to release without this. I will work on the other things

**Comment by sungwoncho** [comment]
@macrozone This seems like a good start. Let's release as a part of `0.4.0`. I personally haven't used storybook and won't be able to test this feature extensively. But the code so far looks good to me. Let me know when it's ready to be merged.

**Comment by macrozone** [comment]
Cool,

We should also discus how to make this optional, if storybook is added by default, etc.

I also think of adding https://github.com/kadirahq/react-storybook-addon-info, but this can be done by modifing the templates.

**Comment by macrozone** [comment]
ok, works now, however, it is not yet optional.

If we make it optional, it should be an option when creating an app. 

Then, on every `mantra generate/destroy component` we should already know, if this app was created with storybook support. Maybe check if .storybook-folder exists.

**Comment by sungwoncho** [comment]
Checking `.storybook` folder sounds doable. Maybe from 0.4.0, we could even store the info in `mantra_cli.yaml`. i.e. `storybook: true`.

Personally I wouldn't really mind if CLI generated storybook even though I don't use it. Started https://talk.mantrajs.com/t/should-mantra-cli-generate-storybook-by-default/383. Let's see how people feel.

**Comment by nadeemja** [comment]
Hi,

Great work guys.

Could you perhaps release an intermediate version with this as-is, and then release one later with optionality?

**Comment by sungwoncho** [comment]
@macrozone would you like to do your first release? The release process is automated in [release.sh](https://github.com/mantrajs/mantra-cli/blob/master/release.sh). Maybe we can do `0.3.14.rc1` and later release `0.3.14`.

Let me know your npm, and I will add you to the project.

**Comment by macrozone** [comment]
@sungwoncho https://www.npmjs.com/~macrozone

I saw that you have a 0.4 branch. I forked from master. Should i rebase / merge from 0.4?

**Comment by sungwoncho** [comment]
@macrozone added you to npm.

yeah. you can bump the release candidate version on 0.4.x and do a release.

**Comment by macrozone** [comment]
ok i did a release and bumped the version.

Everything should included in this PR, including your 0.4 branch. But i do not know whether the release-tag will be transfered.

Can you merge?

**Comment by sungwoncho** [comment]
@macrozone it seems that git tags do not get merged. Feel free to create a tag again and push to master.

**Comment by macrozone** [comment]
I'll try!

btw. templates in yaml-configs work well so far. 👍 

It's also possible to customize storybook-templates which i used to add the "addWithInfo"-plugin

**Comment by sungwoncho** [comment]
Regarding yaml-configs: I think there is a known issue with customizing publication template, because we are supporting collection2 and astronomy.

All in all, this is a good start and we can implement the last item (make generating of storybook optional) if the users want it. Thanks for the hard work.

**Pull request merged**
