### PR TITLE
Add Windows support please

### PR DESCRIPTION
**Pull request by varavut**
Hello,

The create command in current version of mantra-cli is not support Windows. I have try to add some bat file and edit some code to add Windows support as you see below. 

Thank you for your awesome work.

### CODE REVIEW

**Comment by sungwoncho** [comment]
This is a good start but we will have to maintain both `.sh` and `.bat` files.

Is the problem that `.sh` files are not executable on Windows? Then is there a way for us to run them on Windows?

**Comment by varavut** [comment]
Yes, .sh files are not executable on Windows. The only way that I can think is using a tool such as Cygwin or MinGW to emulate Unix-like environment, however that is not easy.

**Comment by sungwoncho** [comment]
Thanks for clarification. @arunoda what's your opinion?

**Comment by arunoda** [comment]
Maintaining both files in kind a hard. But here we've a simple solution.
Instead of using a shell/bash files, let's write them with pure NodeJS.

We can use shelljs for this if needed: https://github.com/shelljs/shelljs

**Comment by sungwoncho** [comment]
I looked at shelljs and it looks like a good solution. @varavut would you like to take charge on this?

**Comment by varavut** [comment]
I have try to replace shell/bash files with shelljs command.
[fc7e8fe](https://github.com/varavut/mantra-cli/commit/fc7e8fe16628123e88fba41a2854de6417bb0fdf)
Is it okay?

**Comment by arunoda** [comment]
Looks good to me.

**Comment by sungwoncho** [comment]
:+1:

**Comment by sungwoncho** [comment]
Released in [0.3.1](https://github.com/mantrajs/mantra-cli/releases/tag/v0.3.1).

**Pull request merged**
